### ISSUE TITLE
Build process with Glide

### ISSUE THREAD

**Issue by sapessi** [awslabs/aws-lambda-go-api-proxy#10]
Moving this from a comment on #9 by @dave-malone to a new issue 

instead of the Makefile, would you be open to other options for building this project? For instance, using Glide we can run all tests with simpler commands:

go test ./... $(glide novendor) --cover

**Comment by SAPessi** [comment]
@dave-malone what are the advantages of Glide of a makefile?

**Comment by dave-malone** [comment]
Whatever mechanism allows us to execute repeatable builds simply, without also running vendored dependency tests, is ok with me. 

The only reason I like Glide is that they provide a convenient way to ignore vendored dependencies when using the multiple package option in test or build.

**Comment by sapessi** [comment]
Closing this since the whole ecosystem has changed quite a bit.
