### ISSUE TITLE
Cannot go get based on the installation instruction

### ISSUE THREAD

**Issue by adhatama** [awslabs/aws-lambda-go-api-proxy#11]
I did `go get github.com/awslabs/aws-lambda-go-api-proxy` like in the README.md but it shows error

>can't load package: package github.com/awslabs/aws-lambda-go-api-proxy: no Go files in /Users/user/Code/golang/src/github.com/awslabs/aws-lambda-go-api-proxy

Did I miss something?

**Comment by israelb** [comment]
I have the same error

**Comment by SAPessi** [comment]
Thanks for the feedback @adhatama and @israelb - I'll fix the instructions. The packages are in specific sub-directories (gin, etc)

**Comment by israelb** [comment]
I figured out:

go get github.com/awslabs/aws-lambda-go-api-proxy/gin

thanks you @SAPessi  Nice library!

**Comment by adhatama** [comment]
It looks like even it gave error above, it still downloaded correctly. The error message is just like some warning. 
And the use of specific sub-directories in `go get` will download all the file in that repo.

I'll close this issue.

**Comment by SAPessi** [comment]
Thanks @adhatama, I'll keep it open for now to track the changes to the README

**Comment by SAPessi** [comment]
Now I can close it :P
