### ISSUE TITLE
Detect Content Type on Write

### ISSUE THREAD

**Issue by haydenwoodhead** [awslabs/aws-lambda-go-api-proxy#16]
It would be nice if this detected content type on Write (just as the standard library does) rather than leave it unset. 

I would be willing to work on this.

**Comment by haydenwoodhead** [comment]
I didn't do a very good job of explaining.

I am trying to have my lambda project return html. If I migrate my project from the http standard library to aws-lamda-go-api-proxy the content type of my pages is no longer set to text/html instead it defaults to application/json if no other content type is set. I can solve this my manually by setting my content type. 

What I am proposing is to call [http.DetectContentType](https://golang.org/pkg/net/http/#DetectContentType) on write if no other content type is set. This is what the standard library does and I think would make this project more of a 'drop-in' replacement for it.

**Comment by SAPessi** [comment]
Ah, thanks @haydenwoodhead, makes sense. I'll do some tests with it over the next couple of days and update the framework.

**Comment by SAPessi** [comment]
Addressed in the latest commit.
