### ISSUE TITLE
Fiber Example Returns 500 Internal Server Error

### ISSUE THREAD

**Issue by mcblair** [awslabs/aws-lambda-go-api-proxy#162]
I was having issues after implementing my lambda with the fiber adapter returning 500 from `fiberLambda.ProxyWithContext`. 

So i blew it all away and built the example alone, uploaded it to a brand new function in AWS, and the behavior is exactly the same. 

When I dump routes, I don't even see the expected `GET` that we wire up.

Example: https://github.com/awslabs/aws-lambda-go-api-proxy/blob/bf16974733133c4d9c4cf6778503f60a703ced9b/examples/fiber/main.go

**Comment by sophatvathana** [comment]
Hi @mcblair , I've the same issue. There is missing port in address https://github.com/awslabs/aws-lambda-go-api-proxy/blob/bf16974733133c4d9c4cf6778503f60a703ced9b/fiber/adapter.go#L132 which make fiber server cannot serve. I've just fixed it by fork and concat the port with r.RemoteAddr. then everything is just working fine.

**Comment by ruralcoder** [comment]
I had the same issue with 0.14, had to revert back to 0.13.3

**Comment by pablodz** [comment]
Same error here 

```bash
  ~  curl https://abc.execute-api.us-east-1.amazonaws.com/default/go-app/health
Internal Server Error

```

**Comment by marvin-w** [comment]
Can confirm this error, can we get the fix merged here and publish a new release?

**Comment by acidjazz** [comment]
> Hi @mcblair, I was having the same issue. There is a missing port in the address
> 
> https://github.com/awslabs/aws-lambda-go-api-proxy/blob/bf16974733133c4d9c4cf6778503f60a703ced9b/fiber/adapter.go#L132
> 
> which make fiber server cannot serve. I've just fixed it by fork and concat the port with r.RemoteAddr. then everything is working fine.

Can I see your fork/PR?

**Comment by acidjazz** [comment]
This issue might be linked to https://github.com/awslabs/aws-lambda-go-api-proxy/issues/175

**Comment by marvin-w** [comment]
#181 will fix this. Until it is released, I'm using.

`github.com/awslabs/aws-lambda-go-api-proxy => github.com/marvin-w/aws-lambda-go-api-proxy v0.14.1`

Feel free to do the same.

**Comment by acidjazz** [comment]
@mcblair why was this marked closed? i don't see a fix anywhere, last release was in Feb
