### ISSUE TITLE
Does the library support streaming responses?

### ISSUE THREAD

**Issue by smark-d** [awslabs/aws-lambda-go-api-proxy#170]
I wrote a handler function in Go that looks like this:

``` golang
func handlerFunc(w http.ResponseWriter, r *http.Request) {
  // Build an HTTP request.
  req, err := http.NewRequest("POST", url, body)
  
  // Send the request and get the response.
  resp, err := client.Do(req)
  
  // Write the response to w.
  io.Copy(w, resp.Body)
}
```

It seems that the function waits for `resp` to be returned before sending back a response, but I'm not sure where's the problem is.

**Comment by its-felix** [comment]
It's currently not supported by this library.

For response streaming you have to:
- set the invoke mode to `RESPONSE_STREAM` on your Lambda
- use the return type `*events.LambdaFunctionURLStreamingResponse` in your handler code (this return type is currently not supported in this library)
- compile your go binary with the build-tag `lambda.norpc`

I have built a similar library myself and just added support for it.
If anyone wants to implement it here, they might have a look into my implementation for streaming responses: https://github.com/its-felix/aws-lambda-go-http-adapter/blob/503bab0e61546d0733fb0c8ebc95bdb5e18e0330/handler/functionurl.go#L140-L228

The trickiest part for me was to decouple the invocation of the underlying adapter (`net/http`, `fiber`, `echo` etc) from the regular call flow.

**Comment by smark-d** [comment]
> It's currently not supported by this library.
> 
> For response streaming you have to:
> 
> * set the invoke mode to `RESPONSE_STREAM` on your Lambda
> * use the return type `*events.LambdaFunctionURLStreamingResponse` in your handler code (this return type is currently not supported in this library)
> * compile your go binary with the build-tag `lambda.norpc`
> 
> I have built a similar library myself and just added support for it. If anyone wants to implement it here, they might have a look into my implementation for streaming responses: https://github.com/its-felix/aws-lambda-go-http-adapter/blob/503bab0e61546d0733fb0c8ebc95bdb5e18e0330/handler/functionurl.go#L140-L228
> 
> The trickiest part for me was to decouple the invocation of the underlying adapter (`net/http`, `fiber`, `echo` etc) from the regular call flow.

Thank you very much, you solved my problem.
