### ISSUE TITLE
fiber adapter broken since v0.14.0 release

### ISSUE THREAD

**Issue by acidjazz** [awslabs/aws-lambda-go-api-proxy#175]
Ever since[ this release ](https://github.com/awslabs/aws-lambda-go-api-proxy/releases/tag/v0.14.0) any attempt to upgrade results in `Internal Server Error` on lambda and no logs in cloudwatch.  This results in all of my Lambda+Fiber+Go projects going down until I hard-code this back to v0.13.3

**Comment by acidjazz** [comment]
I have verified this on 3 different projects by switching back and forth from v0.14.0 to v0.13.3, all go back and forth from working fine to crashing with `Internal Server Error` - only duplicate-able in lambda and no logs

**Comment by acidjazz** [comment]
Issue might be similar to https://github.com/awslabs/aws-lambda-go-api-proxy/issues/162

**Comment by acidjazz** [comment]
@sapessi @bhavik1st can we at least roll these changes back so that a `go get -u` doesnt bring down each environment for each project i have

**Comment by theoribeiro** [comment]
We're having the same issue with the adapter. It would be great if we could roll back these changes. @sapessi @bhavik1st

**Comment by marvin-w** [comment]
#181 will fix this. Until it is released, I'm using.

`replace github.com/awslabs/aws-lambda-go-api-proxy => github.com/marvin-w/aws-lambda-go-api-proxy v0.14.1`

Feel free to do the same.

**Comment by marvin-w** [comment]
@sapessi Any chance we can merge and publish this soon?

**Comment by marvin-w** [comment]
@sapessi Any update?...

**Comment by minuchi** [comment]
I have also the same problem. Is there any update? 😭

**Comment by mfreeman451** [comment]
Lets get this fixed

**Comment by acidjazz** [comment]
For anyone interested v0.2.0 of the [fume fiber adapter](https://github.com/fumeapp/fiber/releases/tag/v0.2.0) no longer requires this library

**Comment by 0angelic0** [comment]
v0.15.0 was released but it didn't fix this issue.....

**Comment by acidjazz** [comment]
@sapessi we noticed you [released an update](https://github.com/awslabs/aws-lambda-go-api-proxy/releases/tag/v0.15.0) - can you please address this pretty serious `6 MONTH OLD` issue

**Comment by mfreeman451** [comment]
I see this issue has been closed, do we have a workaround now?

**Comment by marvin-w** [comment]
It's part of v0.16.0
