### ISSUE TITLE
Generalize adapters

### ISSUE THREAD

**Issue by pirfalt** [awslabs/aws-lambda-go-api-proxy#18]
`chi.Mux`, `gin.Engine`, `gorillamux.Router`, `http.HandlerFunc` and `negroni.Negroni` all implements the `http.Handler` interface, and all there adapter files are strikingly similar. All the adapters could probably be replaced with a single adapter which takes that `http.Handler` interface instead of the concrete implementations.

Which I noticed after opening #17 which adds this to ~~only the handlerfunc package~~ a new httpadapter package. (Which all others could delegate to).

**Comment by sapessi** [comment]
PR merged. Closing issue. Thanks for the contribution @pirfalt and apologies for the delay!

**Comment by kyleyost19** [comment]
To this point being made @pirfalt , you can just remove the gorillamux and handlerfunc packages. You simply cast them to an http.Handler when you instantiate your Handler package with Handler.New().
