### ISSUE TITLE
Gin Specific Headers in Core package

### ISSUE THREAD

**Issue by dave-malone** [awslabs/aws-lambda-go-api-proxy#2]
It seems that Gin specific headers have made their way into the core package. This is confusing for developers wishing to extend support to other frameworks as it seems the core package contains implementation specific details. 

https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/request.go#L25,L30

**Comment by SAPessi** [comment]
You are right, the names are Gin-specific. However, the values are not. I'll change the name of the headers.

**Comment by SAPessi** [comment]
Done, I've changed the header keys to `X-GoLambdaProxy-xxx`.
