### ISSUE TITLE
Does it support local test?

### ISSUE THREAD

**Issue by ShawnOY** [awslabs/aws-lambda-go-api-proxy#23]
Hello,

I run the sample code but it is not open any port, it's available to support local testing?

**Comment by sapessi** [comment]
You could start the application in local by starting the framework with the normal code in your main method. Perhaps you can look for environment variables to decide whether you are running in local dev or on Lambda. My recommendation would be to use the SAM CLI to emulate Lambda and API Gateway in local - this allows you to better emulate Lambda's behavior.

**Comment by ShawnOY** [comment]
Thank you @sapessi

**Comment by pedrohba1** [comment]
Just to specify, you can start local development using:

```
sam local start-api -t ./apps/api/template.yaml
```
And you need to specify your `tempalte.yaml` if it's not in the root directory.
