### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by srikanthkumar** [awslabs/aws-lambda-go-api-proxy#24]
How may I enable CORS for this setup? Please help

**Comment by sapessi** [comment]
You can use API Gateway to set up CORS for you APIs. This way the pre-flight requests (OPTION) don't even need to trigger your Lambda. [Docs here](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html)

**Comment by srikanthkumar** [comment]
Thanks Sapessi, It worked.
