### ISSUE TITLE
Multi value query string param?

### ISSUE THREAD

**Issue by maros7** [awslabs/aws-lambda-go-api-proxy#25]
Multi value query string params are disregarded. Or I’m I missing something? https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/request.go#L121-L132

**Comment by sapessi** [comment]
We haven't added support for multivalue headers and query strings yet. It's on my TODO list. I hope to get to it by mid-Feb. Obviously PRs are very welcome.
