### ISSUE TITLE
Are Headers absolutely required in response?

### ISSUE THREAD

**Issue by dave-malone** [awslabs/aws-lambda-go-api-proxy#3]
An http.HandlerFunc can return a response without any headers by default, and as far as I know, it's a valid http response to have an empty set of headers.

https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/response.go#L63,L65

**Comment by SAPessi** [comment]
I'd be suspicious of responses that return 0 headers. Is there a case where this may happen?

**Comment by dave-malone** [comment]
The default behavior of Golang's http.HandlerFunc is to write a response without headers (headers slice is empty). Enforcing that a header is always returned would create an awkward scenario for developers who wouldn't normally use any headers in their response (see my PR's test case for handlerfunc).

**Comment by SAPessi** [comment]
Done.
