### ISSUE TITLE
Add support for echo

### ISSUE THREAD

**Issue by watermelo** [awslabs/aws-lambda-go-api-proxy#35]

**Comment by surmer** [comment]
Hi @watermelo any chance you could also support a v4 echo router as well? I'm trying to use it with openapi-generator go-server and the code openapi-generator creates uses "github.com/labstack/echo/v4", which conflicts with the echo adapter types.

**Comment by sam3d** [comment]
@jackwellsxyz I found the contents of the `echo/adapter.go` to be small enough that I just copy and pasted the code into my own internal package and then just updated the import to use `v4`. It still functions the same, except with the new types.

It's an unfortunate thing to have to do, but it's completely functional for now.
