### ISSUE TITLE
Tag latest release

### ISSUE THREAD

**Issue by jackwellsxyz** [awslabs/aws-lambda-go-api-proxy#39]
Hello! Could you please tag the repo with an updated version number when you're ready? I'd love to take advantage of the echo lambda handler, but go get won't import the echo handler unless it's in a tagged release. Thank you!

**Comment by jackwellsxyz** [comment]
Hi @sapessi, do you think we might be ready for a new tag? It would help me a ton!

**Comment by sapessi** [comment]
I was trying to split the repo into multiple modules before adding the new tag. Running into all sort of issues with it. I'll have another go today.

**Comment by sapessi** [comment]
I've tagged a `0.4.0` in the repo @jackwellsxyz

**Comment by jackwellsxyz** [comment]
Fantastic, thank you!
