### ISSUE TITLE
Support for echo router v4

### ISSUE THREAD

**Issue by jackwellsxyz** [awslabs/aws-lambda-go-api-proxy#41]
Hello! Could we upgrade the echo module to support version 4? I have a dependency that returns a v4 echo router (and it seems to be the favored version on the github page), but I can't integrate it with the aws-lambda-go-api-proxy. I can do a very quick pull request that either adds support for both versions, or alternatively changes the import to github.com/labstack/echo/v4 if you'd like.

Thanks!

**Comment by sapessi** [comment]
Hi @jackwellsxyz - v4 of echo is a major release that includes breaking changes. I'll dig deeper into what the changes are and if needed I'll pull it in a separate package (`/echov4`).

**Comment by Ropelatto** [comment]
When will it be released?

**Comment by tyd** [comment]
@sapessi Any update as to when this will be merged and released? Thanks

**Comment by sapessi** [comment]
#50 addresses this. There are some changes needed but we should be close.

**Comment by excavador** [comment]
Any updates?

**Comment by sapessi** [comment]
I'll look at this between today and tomorrow. Apologies for the delay.

**Comment by jnathanh** [comment]
It looks like the major version change was switching to go modules. I copied https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/echo/adapter.go and added the `/v4` to the echo import and it's working just fine.

**Comment by lucasmdomingues** [comment]
v4 is available ?

**Comment by sapessi** [comment]
Closing since #71 was just merged and `v0.8.0` tagged as a release
