### ISSUE TITLE
Support for MultiValue Request Headers

### ISSUE THREAD

**Issue by Bryanide** [awslabs/aws-lambda-go-api-proxy#63]
Hello, there is currently an issue where multi-value request headers are not properly being handled and set. This causes 406 errors in requests with multi-value headers enabled.

MultiValueHeaders is a `map[string][]string` whereas Headers is a `map[string]string`

https://github.com/awslabs/aws-lambda-go-api-proxy/blob/8564c1ce2a1c8ccf3571fb1ffa2c6cef1cbf56c0/core/request.go#L193

I have addressed this issue in https://github.com/awslabs/aws-lambda-go-api-proxy/pull/62

**Comment by jt0** [comment]
PR merged.
