### ISSUE TITLE
Support compression/GZIP on ALB

### ISSUE THREAD

**Issue by NotSoSuper** [awslabs/aws-lambda-go-api-proxy#76]
Hello,

Is there anyway to support GZIP while using the ALB? I know the API GW supports compression, however, I'm not using that.

I've seen that there isn't "full" support for ALB right now, but it's working just fine for me.

Any tips would be appreciated, thanks!

**Comment by NotSoSuper** [comment]
Figured out a solution, in general you must force enable base64 encoding for the return (gzipped) body.

**Comment by jcunhafonte** [comment]
@NotSoSuper Can you elaborate on the solution, please?
